"use client";
import { useEffect, useRef, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { api } from "@/lib/api";
import MeetingRoom from "@/components/meeting/MeetingRoom";

export default function MeetingPage() {
  const { meetingId } = useParams(); const router = useRouter(); const previewRef = useRef(null); const streamRef = useRef(null);
  const [meeting, setMeeting] = useState(null), [user, setUser] = useState(null), [password, setPassword] = useState(""), [camera, setCamera] = useState(true), [microphone, setMicrophone] = useState(true), [connection, setConnection] = useState(null), [error, setError] = useState("");
  useEffect(() => { Promise.all([api(`/meetings/${meetingId}`), api("/auth/me")]).then(([m, a]) => { setMeeting(m.meeting); setUser(a.user); }).catch((e) => setError(e.message)); }, [meetingId]);
  useEffect(() => { let active = true; navigator.mediaDevices?.getUserMedia({ video: true, audio: true }).then((stream) => { if (!active) return stream.getTracks().forEach((track) => track.stop()); streamRef.current = stream; if (previewRef.current) previewRef.current.srcObject = stream; }).catch(() => setError("Camera/microphone permission is unavailable. You can still join.")); return () => { active = false; streamRef.current?.getTracks().forEach((track) => track.stop()); }; }, []);
  useEffect(() => { streamRef.current?.getVideoTracks().forEach((track) => { track.enabled = camera; }); }, [camera]); useEffect(() => { streamRef.current?.getAudioTracks().forEach((track) => { track.enabled = microphone; }); }, [microphone]);
  async function join() { try { setError(""); await api(`/meetings/${meetingId}/join`, { method: "POST", body: JSON.stringify({ password }) }); const { token, url } = await api(`/livekit/token?room=${encodeURIComponent(meetingId)}`); streamRef.current?.getTracks().forEach((track) => track.stop()); setConnection({ token, url, audio: microphone, video: camera }); } catch (e) { setError(e.message); } }
  if (connection) return <MeetingRoom {...connection} meetingId={meetingId} name={user?.name} title={meeting?.title} onLeave={() => router.push("/dashboard")} />;
  return <main className="flex min-h-screen items-center justify-center bg-slate-950 p-4 text-white"><section className="w-full max-w-3xl rounded-3xl bg-slate-900 p-5 shadow-2xl sm:p-8"><p className="text-blue-400">VideoMeet waiting room</p><h1 className="mt-2 text-2xl font-bold">{meeting?.title || "Loading meeting..."}</h1><p className="mt-1 text-sm text-slate-400">Meeting ID: {meetingId}</p><div className="mt-6 grid gap-6 md:grid-cols-[1.4fr_1fr] md:items-center"><div className="relative aspect-video overflow-hidden rounded-2xl bg-slate-800"><video ref={previewRef} autoPlay muted playsInline className={`h-full w-full object-cover ${camera ? "" : "hidden"}`} />{!camera && <div className="flex h-full items-center justify-center text-5xl">{user?.name?.[0] || "?"}</div>}<span className="absolute bottom-3 left-3 rounded-lg bg-black/60 px-2 py-1 text-sm">{user?.name || "You"}</span></div><div><p className="text-sm text-slate-300">Check your setup before joining.</p><div className="mt-4 flex gap-2"><button onClick={() => setMicrophone(!microphone)} className="rounded-xl border border-slate-700 px-4 py-3">{microphone ? "Mic on" : "Mic off"}</button><button onClick={() => setCamera(!camera)} className="rounded-xl border border-slate-700 px-4 py-3">{camera ? "Camera on" : "Camera off"}</button></div>{meeting?.hasPassword && <input value={password} onChange={(e) => setPassword(e.target.value)} type="password" placeholder="Meeting password" className="mt-4 h-11 w-full rounded-xl px-3 text-slate-900" />}{error && <p className="mt-4 text-sm text-red-300">{error}</p>}<button disabled={!meeting || !user} onClick={join} className="mt-5 w-full rounded-xl bg-blue-600 px-5 py-3 font-semibold disabled:opacity-50">Join now</button></div></div></section></main>;
}
