"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/api";

export default function Dashboard() {
  const router = useRouter(); const [user, setUser] = useState(null), [title, setTitle] = useState(""), [password, setPassword] = useState(""), [scheduledAt, setScheduledAt] = useState(""), [meetings, setMeetings] = useState([]), [error, setError] = useState("");
  useEffect(() => { Promise.all([api("/auth/me"), api("/meetings")]).then(([a, b]) => { setUser(a.user); setMeetings(b.meetings); }).catch(() => router.replace("/login")); }, [router]);
  async function create(e) { e.preventDefault(); try { const { meeting } = await api("/meetings", { method: "POST", body: JSON.stringify({ title, password, scheduledAt: scheduledAt || undefined }) }); router.push(`/meeting/${meeting.meetingId}`); } catch (e) { setError(e.message); } }
  async function logout() { await api("/auth/logout", { method: "POST" }); router.push("/"); }
  return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-5"><a href="/" className="text-xl font-bold text-blue-600">VideoMeet</a><nav className="flex items-center gap-4 text-sm"><a href="/history">History</a><a href="/settings">Settings</a><button onClick={logout} className="text-slate-500">Log out</button></nav></div></header><section className="mx-auto max-w-6xl px-4 py-12"><p className="text-blue-600">Dashboard</p><h1 className="mt-2 text-4xl font-bold text-slate-900">Welcome back{user ? `, ${user.name}` : ""}</h1><div className="mt-8 grid gap-5 sm:grid-cols-2"><form onSubmit={create} className="rounded-2xl bg-blue-600 p-7 text-white shadow-lg"><b className="text-xl">Create a meeting</b><input required value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Meeting title" className="mt-5 h-11 w-full rounded-lg px-3 text-slate-900" /><input value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Optional password" className="mt-3 h-11 w-full rounded-lg px-3 text-slate-900" /><input type="datetime-local" value={scheduledAt} onChange={(e) => setScheduledAt(e.target.value)} className="mt-3 h-11 w-full rounded-lg px-3 text-slate-900" /><button className="mt-3 rounded-lg bg-white px-4 py-2 font-semibold text-blue-700">Create now</button>{error && <p className="mt-2 text-sm text-red-100">{error}</p>}</form><button onClick={() => router.push("/join")} className="rounded-2xl border bg-white p-7 text-left shadow-sm"><b className="text-xl">Join a meeting</b><span className="mt-2 block text-slate-500">Use a meeting ID or link</span></button></div><h2 className="mt-12 text-2xl font-bold">Recent meetings</h2><div className="mt-4 grid gap-3">{meetings.length ? meetings.map((m) => <div key={m._id} className="flex items-center justify-between rounded-xl bg-white p-4 shadow-sm"><div><b>{m.title}</b><p className="text-sm text-slate-500">{m.meetingId} · {m.status}{m.scheduledAt ? ` · ${new Date(m.scheduledAt).toLocaleString()}` : ""}</p></div><button onClick={() => router.push(`/meeting/${m.meetingId}`)} className="rounded-lg bg-blue-600 px-3 py-2 text-sm text-white">Join</button></div>) : <p className="text-slate-500">No meetings yet.</p>}</div></section></main>;
}
